apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mssqlrestorerequests.dbaas.cozy.io
spec:
  group: dbaas.cozy.io
  scope: Namespaced
  names:
    plural: mssqlrestorerequests
    singular: mssqlrestorerequest
    kind: MSSQLRestoreRequest
    shortNames:
      - mssqlrr
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - instanceRef
                - targetTime
                - newInstanceName
              properties:
                instanceRef:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
                targetTime:
                  type: string
                newInstanceName:
                  type: string
                databases:
                  type: array
                  items:
                    type: string
                targetConnection:
                  type: object
                  properties:
                    host:
                      type: string
                    port:
                      type: integer
                    user:
                      type: string
                    passwordSecretRef:
                      type: object
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                targetStorage:
                  type: object
                  properties:
                    pvcName:
                      type: string
                    storageClassName:
                      type: string
                    size:
                      type: string
                    accessModes:
                      type: array
                      items:
                        type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                restoreJobName:
                  type: string
                message:
                  type: string
