apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mssqlinstances.dbaas.cozy.io
spec:
  group: dbaas.cozy.io
  scope: Namespaced
  names:
    plural: mssqlinstances
    singular: mssqlinstance
    kind: MSSQLInstance
    shortNames:
      - mssqli
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - connection
              properties:
                connection:
                  type: object
                  required:
                    - host
                    - port
                    - user
                    - passwordSecretRef
                  properties:
                    host:
                      type: string
                    port:
                      type: integer
                    user:
                      type: string
                    passwordSecretRef:
                      type: object
                      required:
                        - name
                        - key
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                destination:
                  type: object
                  properties:
                    endpoint:
                      type: string
                    bucket:
                      type: string
                    prefix:
                      type: string
                    secretRef:
                      type: object
                      required:
                        - name
                      properties:
                        name:
                          type: string
                    tls:
                      type: object
                      properties:
                        insecureSkipVerify:
                          type: boolean
                          default: false
                storage:
                  type: object
                  properties:
                    managePVC:
                      type: boolean
                      default: true
                    manageSourcePVC:
                      type: boolean
                    manageBackupPVC:
                      type: boolean
                    manageTargetPVC:
                      type: boolean
                    sourceData:
                      type: object
                      properties:
                        pvcName:
                          type: string
                        storageClassName:
                          type: string
                        size:
                          type: string
                          default: "100Gi"
                        accessModes:
                          type: array
                          items:
                            type: string
                    backupData:
                      type: object
                      properties:
                        pvcName:
                          type: string
                        storageClassName:
                          type: string
                        size:
                          type: string
                          default: "200Gi"
                        accessModes:
                          type: array
                          items:
                            type: string
                    targetData:
                      type: object
                      properties:
                        storageClassName:
                          type: string
                        size:
                          type: string
                          default: "100Gi"
                        accessModes:
                          type: array
                          items:
                            type: string
                allDatabases:
                  type: boolean
                  default: true
                databases:
                  type: array
                  items:
                    type: string
                retentionDays:
                  type: integer
                  minimum: 1
                  maximum: 30
                  default: 30
                fullBackupSchedule:
                  type: string
                  default: "0 0 * * *"
                logBackupIntervalMinutes:
                  type: integer
                  minimum: 1
                  default: 5
                mode:
                  type: string
                  enum: [native_url, disk_then_upload, local_pvc]
                  default: local_pvc
                dryRun:
                  type: boolean
                  default: false
                executor:
                  type: object
                  properties:
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                targets:
                  type: object
                  properties:
                    rpoTarget:
                      type: string
                      default: "5m"
                    rtoTarget:
                      type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                backupPolicyName:
                  type: string
                sourcePVCName:
                  type: string
                backupPVCName:
                  type: string
                message:
                  type: string
